#include<iostream.h>
#include<conio.h>

// take input as name rolnumber and marks and display
// create a function  with argument no return
void displayStudentDetials(int n,int roll,float marks){

 cout<<n<<endl; // endl use for new line
 cout<<roll<<endl;
 cout<<marks<<endl;


}

void main(){
clrscr();

    // char x[]="satyam";
     int r=102;
     float m=430;
    int x= 20;
 displayStudentDetials(x,r,m);
 getch();
}